### ISSUE TITLE
Ray shuffle not working 

### ISSUE THREAD

**Issue by austin362667** [apache/datafusion-ray#10]
I got an error on Mac: `Memory pointer from external source (e.g, FFI) is not aligned with the specified scalar type. Before importing buffer through FFI, please make sure the allocation is aligned.` while using ray shuffle on Datafusion Ray against TPC-H.

After that the Ray worker died.

@andygrove saw this error when trying to run the example on Linux, but it worked on Mac.

@franklsf95  Any suggestion would be helpful! I appreciate it!

**Comment by andygrove** [comment]
Possible workaround in https://github.com/apache/arrow/issues/43552

**Comment by andygrove** [comment]
arrow-rs already has a fix for this in https://github.com/apache/arrow-rs/pull/6472 and is included in 53.1.0, so this should be fixed when we upgrade to a version of DataFusion that uses this Arrow version
