### ISSUE TITLE
Improve k8s documentation to cover upgrading to Ray 2.37.0

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-ray#30]
I followed the k8s docs and it set up a cluster using Ray 2.9.0. DataFusion Ray requires Ray 2.37.0, so I think that we should add documentation explaining how to upgrade.

**Comment by vakarisbk** [comment]
Cluster version is determined by the container image that is used to launch the cluster (step 3 in the docs). 

The default container image is `rayproject/ray:2.9.0`. The docs show how to override the default image and to use the image built from k8s/Dockerfile which uses ray 2.37.0 and includes all dependencies.

So most likely the cluster is deployed using the default image. To confirm that, run `kubectl get pod [RAY_POD_NAME] -o jsonpath='{.spec.containers[*].image}'` 

If that's the case, do `helm delete datafusion-ray` and redo step 3.

**Comment by andygrove** [comment]
Thanks. I hadn't understood that from reading the docs, but it makes sense now.
